### ISSUE TITLE
How to pass environment variables?

### ISSUE THREAD

**Issue by mariocasciaro** [tableflip/boss#26]
Is there a way to provide a set of env variables when starting a process?

**Comment by achingbrain** [comment]
A process should inherit from it's environment so:

```sh
MY_VAR=foo bs start myscript.js
```

**Comment by mariocasciaro** [comment]
Is that maintained across restarts?

**Comment by achingbrain** [comment]
It should be, yes.  You can check by killing boss then examining the contents of `/etc/boss/processes.json`

**Comment by mariocasciaro** [comment]
Yes, sorry I tried it myself and it seems to be perfectly working, thanks!
