### ISSUE TITLE
Permissions issues when running `bs remoteconfig/useradd/kill `

### ISSUE THREAD

**Issue by mariocasciaro** [tableflip/boss#28]
Specifically:
```
sudo bs remoteconfig
warn: You do not appear to have sufficient permissions
```

```
sudo bs useradd alex
warn: You do not appear to have sufficient permissions
```

```
sudo bs kill
warn: You do not appear to have sufficient permissions
```

boss daemon is running as root, my user is in the boss group.
Any advice?

**Comment by achingbrain** [comment]
That usually means something went wrong in the daemon. Could you take a look at the boss logs under /var/log/boss and post any stack traces?

**Comment by mariocasciaro** [comment]
Apparently there are no stack traces or errors besides those generated by the supervised app. However after restarting the machine (and thus restarting the daemon) everything seems to work properly now. I'll reopen the issue if I stumble upon the problem again.
