### ISSUE TITLE
Picking up wrong node version with node manager "n"

### ISSUE THREAD

**Issue by jzumbrun** [tableflip/boss#29]
I have the node manager "n" to switch to 0.10.36 and boss still throws and error. I console logged the version boss is seeing around line: https://github.com/tableflip/boss/blob/b41d5d53b3f5e97f16a21b9f9f15700ef9bb8af7/lib/local/LocalDaemon.js#L28

and this is the output I get:

```
[vagrant@localhost raventracking]$ sudo bs start -n raven -a '-s raven' tracking/index.js 
0.10.22 ### this is from the console.log() I added
error: Failed to start /opt/raventracking/tracking/index.js
error:  message=Script tracking/index.js does not exist, code=INVALID ## Also this is not correct. The file is there. I tabbed to get to it so bash definitely sees it.
[vagrant@localhost raventracking]$ node -v
v0.10.36 ## node -v is saying it higher than the required 0.10.29

```

Any thoughts?

**Comment by achingbrain** [comment]
What happens if you run:

```sh
$ sudo env node -v
```

**Comment by jzumbrun** [comment]
Guess my sudo env is on a different version:
```
[vagrant@localhost raventracking]$ sudo env node -v
v0.10.22
[vagrant@localhost raventracking]$ node -v
v0.10.36

```

**Comment by achingbrain** [comment]
Try becoming root and use n to set the node version available for root or failing that, upgrade the system version to something above 0.10.29.

**Comment by jzumbrun** [comment]
I got it to work outside of vagrant. Vagrant was just giving me issues.
