### ISSUE TITLE
coffeescript support?

### ISSUE THREAD

**Issue by maxlath** [tableflip/boss#31]
hi, thank you for this project!
what would it take to make it run a coffeescript program?
Taking inspiration on what they are doing at [node-supervisor](https://github.com/isaacs/node-supervisor/blob/master/lib/supervisor.js), I tried, full of hope, to just replace `which node` executor by `which coffee` without much success...
It fails when `ProcessWrapper.prototype._startProcess` tries to `require(script)`: I guess you can't require a coffeescript module from normal javascript, is that it? If so, it could only work if the whole boss was converted to coffeescript, right?

**Comment by achingbrain** [comment]
This has been released in boss 2.6.0 - I don't really use coffeescript so please give it a go and open an issue if you find any problems.

**Comment by maxlath** [comment]
thanks! will do!
